; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "StealerHunter"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "CyberSecurity Lab"
#define MyAppExeName "StealerHunter.exe"
#define MyAppAssocName "StealerHunter Security Scanner"
#define MyAppId "StealerHunter-Security-Suite"
#define AppUserModelId "StealerHunter"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Require administrator privilege for deep NTFS MFT scans, quarantine, and registry protection
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=installer_output
OutputBaseFilename=StealerHunter_Setup_v{#MyAppVersion}
SetupIconFile=StealerHunter\Assets\app.ico
UninstallDisplayIcon={app}\Assets\app.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
CloseApplications=force
CloseApplicationsFilter={#MyAppExeName}
MinVersion=10.0

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startupicon"; Description: "Jalankan StealerHunter otomatis saat Windows startup (proteksi di latar belakang)"; GroupDescription: "Proteksi Real-time:"; Flags: checkedonce

[Files]
; Self-contained .NET 8 publication including all runtimes, coreclr, and dependencies
Source: "StealerHunter\publish\win-x64\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Source icon for uninstall and shortcuts
Source: "StealerHunter\Assets\app.ico"; DestDir: "{app}\Assets"; Flags: ignoreversion

[Icons]
; Start menu shortcut with custom 2D Cyber Shield icon, AppUserModelID, and WorkingDir
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; IconFilename: "{app}\Assets\app.ico"; AppUserModelID: "{#AppUserModelId}"
; Desktop shortcut
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; IconFilename: "{app}\Assets\app.ico"; Tasks: desktopicon; AppUserModelID: "{#AppUserModelId}"

[Registry]
; Clean up any legacy direct-exe HKLM registry Run entry
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueName: "{#MyAppName}"; Flags: deletevalue uninsdeletevalue
; Register HKCU Run entry to trigger Task Scheduler (enables visible listing in Windows Task Manager Startup Apps)
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "{#MyAppName}"; ValueData: """{sys}\schtasks.exe"" /run /tn ""{#MyAppName}"""; Flags: uninsdeletevalue; Tasks: startupicon

[Run]
; 1. Register elevated Task Scheduler startup task (bypasses Windows UAC logon block for admin apps)
Filename: "{sys}\schtasks.exe"; Parameters: "/Create /TN ""{#MyAppName}"" /TR """"'""{app}\{#MyAppExeName}""' --silent"" /SC ONLOGON /RL HIGHEST /F"; Flags: runhidden; Tasks: startupicon
; 2. Launch program after setup
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runascurrentuser

[UninstallRun]
; Gracefully terminate running StealerHunter before uninstallation
Filename: "taskkill.exe"; Parameters: "/F /IM {#MyAppExeName}"; Flags: runhidden; RunOnceId: "StopStealerHunter"
; Remove startup Task Scheduler entry if created
Filename: "{sys}\schtasks.exe"; Parameters: "/Delete /TN ""{#MyAppName}"" /F"; Flags: runhidden; RunOnceId: "RemoveStealerHunterTask"

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
